workflows:
  ios-simulator-workflow:
    name: Unity iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      unity: 2022.3.17f1
      xcode: latest

    scripts:
      - name: Verify Unity is available
        script: |
          which unity-editor
          unity-editor --version

      - name: Build iOS project with Unity
        script: |
          unity-editor \
            -batchmode \
            -quit \
            -projectPath . \
            -executeMethod BuildiOS.Build \
            -logFile unity.log

      - name: Build iOS Simulator app
        script: |
          cd Builds/iOS
          xcodebuild \
            -workspace Unity-iPhone.xcworkspace \
            -scheme Unity-iPhone \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build

    artifacts:
      - Builds/iOS/build/**/Products/Debug-iphonesimulator/*.app
      - unity.log
